# Classifying Movie Reviews

In [33]:
from keras import models
from keras import layers
import numpy as np

In [34]:
from keras.datasets import imdb
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=10000)

In [35]:
word_to_index = imdb.get_word_index()
word_to_index.get('unbelievable')

1294

In [36]:
index_to_word = dict([(values, keys) for (keys, values) in word_to_index.items()])
display(len(index_to_word))

88584

In [37]:
# [index_to_word.get(i-3, '?') for i in x_train[0]]
' '.join([index_to_word.get(i-3, '_') for i in x_train[0]])

"_ this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert _ is an amazing actor and now the same being director _ father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for _ and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also _ to the two little boy's that played the _ of norman and paul they were just brilliant children are often left out of the _ list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you th

In [38]:
x_train_oh = np.zeros((len(x_train), 10000))
for i in np.arange(x_train.shape[0]):
    x_train_oh[i, np.array(x_train[i])] = 1.
    
display(x_train_oh[0])
display(y_train[0])

x_test_oh = np.zeros((len(x_test), 10000))
for i in np.arange(x_test.shape[0]):
    x_test_oh[i, np.array(x_test[i])] = 1.
    
display(x_test_oh[0])
display(y_test[0])

array([0., 1., 1., ..., 0., 0., 0.])

1

array([0., 1., 1., ..., 0., 0., 0.])

0

In [47]:
model = models.Sequential()
model.add(layers.Dense(units=16, activation='relu', input_shape=(10000, )))
model.add(layers.Dense(units=16, activation='relu'))
model.add(layers.Dense(units=1, activation='sigmoid'))

In [48]:
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

In [49]:
model.fit(x=x_train_oh, y=y_train, 
          epochs=20, batch_size=256, 
          validation_data=(x_test_oh, y_test))

Train on 25000 samples, validate on 25000 samples
Epoch 1/20
25000/25000 [==============================] - 2s 87us/step - loss: 0.6858 - acc: 0.5638 - val_loss: 0.6721 - val_acc: 0.6390
Epoch 2/20
25000/25000 [==============================] - 2s 78us/step - loss: 0.6431 - acc: 0.6961 - val_loss: 0.6101 - val_acc: 0.7359
Epoch 3/20
25000/25000 [==============================] - 2s 82us/step - loss: 0.5717 - acc: 0.7760 - val_loss: 0.5401 - val_acc: 0.7910
Epoch 4/20
25000/25000 [==============================] - 2s 82us/step - loss: 0.5043 - acc: 0.8094 - val_loss: 0.4804 - val_acc: 0.8157
Epoch 5/20
25000/25000 [==============================] - 2s 82us/step - loss: 0.4475 - acc: 0.8302 - val_loss: 0.4314 - val_acc: 0.8294
Epoch 6/20
25000/25000 [==============================] - 2s 82us/step - loss: 0.4023 - acc: 0.8447 - val_loss: 0.3973 - val_acc: 0.8396
Epoch 7/20
25000/25000 [==============================] - 2s 79us/step - loss: 0.3705 - acc: 0.8541 - val_loss: 0.3740 - val_acc

In [60]:
target_good_input = "This anime is simply amazing! The way it is animated, the soundtrack, the characters, the story, the thrill and the suspense. All in one action-packed anime. One of the best so far. As it has only 9 episodes as of now ... many critics say that it is way too early to rate an anime. But, according to me, this is pure class. The soundtrack's tempo varies according to the situation and this makes it more exciting. The ending of the episode is something that NO one will look forward to as NO one will want it to end. A must watch for every anime lover and of course the manga is available as well. Although a bit gory, the epicness makes up for it! You know those animes that catch your eye from the first episode, this is one of them."
target_good_input = target_good_input.replace('!', '')
target_good_input = target_good_input.replace('.', '')
target_good_input = target_good_input.replace(',', '')
target_good_input = target_good_input.replace(';', '')
target_good_input = target_good_input.split(' ')
target_good_input = [word_to_index.get(x, '_') for x in target_good_input]
# display(x_target)
target_good_input = [x for x in target_good_input if (x != '_')]
target_good_input = [x for x in target_good_input if (int(x) < 10000)]
# display(x_target)
x_good_target = np.zeros((1, 10000))
x_good_target[0, target_good_input] = 1.

model.predict(x_good_target)

array([[0.86891466]], dtype=float32)

In [61]:
target_bad_input  = "I watched this anime a couple of days ago and i have to say this is an embarrassment to Japanese people. Being Japanese myself i though that I would enjoy it, as I have watched many anime's before this, unfortunately I don't think I will ever watch an anime again after this because it is absolutely rubbish and made me feel sick. This has to be the worst show that has ever been aired on TV. The voice acting is absolutely awful, the animator needs drawing lessons and the writer....... well he needs to learn what a good story is. Many would say that the rating I have given this TV show is a bit to harsh, but believe me this is the most overrated TV show the universe has ever come across, In my opinion this doesn't even deserve 1 star. Seriously, if you've been considering to watch this TV show don't it's bad. P.S. Pikachu and Cubone need to have more screen time, their probably the only good"
target_bad_input = target_bad_input.replace('!', '')
target_bad_input = target_bad_input.replace('.', '')
target_bad_input = target_bad_input.replace(',', '')
target_bad_input = target_bad_input.replace(';', '')
target_bad_input = target_bad_input.split(' ')

target_bad_input = [word_to_index.get(x, '_') for x in target_bad_input]
# display(x_target)
target_bad_input = [x for x in target_bad_input if (x != '_')]
target_bad_input = [x for x in target_bad_input if (int(x) < 10000)]
# display(x_target)
x_bad_input = np.zeros((1, 10000))
x_bad_input[0, x_bad_input.astype(int)] = 1.

model.predict(x_bad_input)

array([[0.5187677]], dtype=float32)